# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3538a973d3134a4bb17812c92b00af8b3af73ab0d9480827d378e9e0a189444d8ed4214145e145be35a85f45553ff8f7f7a3265a02fa8404dbbe88ce92ffe291

test:
  secret_key_base: c6ebc2535a5bdd3763df77866b31bd608b429f06a05c2df1d7d40cf7dd9cd8a058c18237115d96bbfe437befef7fabd3da8836b9a2d8abe96cc26c24e6e05675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
